using ProfitRobots.StrategyGenerator.Model;
using System.IO;
using System.Linq;
using System.Text;

namespace ProfitRobots.StrategyGenerator.PineScript
{
    /// <summary>
    /// Generates code for the TradingView.com (Pine Script)
    /// </summary>
    public class StrategyGenerator : IStrategyGenerator
    {
        public string Generate(MetaModel model)
        {
            StringBuilder code = new StringBuilder();
            code.AppendLine("//Generated by Profit Robots strategy generator")
                .AppendLine("//http://profitrobots.com")
                .AppendLine("//@version=3")
                .AppendLine($"strategy(\"{model.Name}\", overlay = true, default_qty_type=strategy.percent_of_equity, default_qty_value=5)");

            code.Append(ParametersFormatter.GenerateCode(model.Parameters));
            code.Append(SourceFormatter.GenerateCode(model.Sources));
            code.Append(ActionsFormatter.FormatActions(model.Actions));
            return code.ToString();
        }

        public string GenerateFileName(string strategyName)
        {
            return Path.GetInvalidFileNameChars().Aggregate(strategyName, (current, c) => current.Replace(c.ToString(), string.Empty)) + ".txt";
        }

    }
}
